language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib; fi
    - pip install -r requirements.txt
    - pip install python-coveralls
script:
    - nosetests --with-coverage --cover-package=testvibe --cover-inclusive --cover-erase tests/
after_success:
    - coveralls
